#!/usr/bin/env bash
set -Eeuo pipefail

# Recursively run SiYuan CLI --help for all subcommands and collect the output into a Markdown document.
# Default output: $PWD/siyuan-cli-help.md

SIYUAN_BIN="${SIYUAN_BIN:-}"
OUTPUT_FILE="$PWD/siyuan-cli-help.md"
MAX_DEPTH="${MAX_DEPTH:-20}"

usage() {
  cat <<'USAGE'
Usage:
  siyuan-cli-help-export.sh [options]

Options:
  -o, --output FILE       Specify the output Markdown file
  -b, --bin PATH          Path or command name of the siyuan executable
      --max-depth NUMBER  Maximum recursion depth (default 20)
  -h, --help              Show this help

Environment variables:
  SIYUAN_BIN              Same as --bin
  MAX_DEPTH               Same as --max-depth

Examples:
  ./siyuan-cli-help-export.sh
  ./siyuan-cli-help-export.sh -o "$HOME/Documents/siyuan-cli-help.md"
  SIYUAN_BIN="$HOME/.local/bin/siyuan" ./siyuan-cli-help-export.sh
USAGE
}

while (($# > 0)); do
  case "$1" in
    -o|--output)
      [[ $# -ge 2 ]] || { echo "❌ $1 requires a file path" >&2; exit 2; }
      OUTPUT_FILE="$2"
      shift 2
      ;;
    -b|--bin)
      [[ $# -ge 2 ]] || { echo "❌ $1 requires a command or path" >&2; exit 2; }
      SIYUAN_BIN="$2"
      shift 2
      ;;
    --max-depth)
      [[ $# -ge 2 ]] || { echo "❌ $1 requires a number" >&2; exit 2; }
      MAX_DEPTH="$2"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "❌ Unknown argument: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

if ! [[ "$MAX_DEPTH" =~ ^[0-9]+$ ]] || ((MAX_DEPTH < 1)); then
  echo "❌ --max-depth must be a positive integer" >&2
  exit 2
fi

if [[ -z "$SIYUAN_BIN" ]]; then
  SIYUAN_BIN="$(command -v siyuan || command -v SiYuan-Kernel || true)"
fi

if [[ -z "$SIYUAN_BIN" ]]; then
  echo "❌ Could not find the siyuan or SiYuan-Kernel command" >&2
  echo "   Make sure the CLI is in PATH, or use --bin to specify the full path." >&2
  exit 1
fi

if ! SIYUAN_PATH=$(command -v -- "$SIYUAN_BIN" 2>/dev/null); then
  if [[ -x "$SIYUAN_BIN" ]]; then
    SIYUAN_PATH="$SIYUAN_BIN"
  else
    echo "❌ Executable not found: $SIYUAN_BIN" >&2
    echo "   Make sure the CLI is in PATH, or use --bin to specify the full path." >&2
    exit 1
  fi
fi

ROOT_NAME=$(basename -- "$SIYUAN_PATH")
OUTPUT_DIR=$(dirname -- "$OUTPUT_FILE")
mkdir -p -- "$OUTPUT_DIR"

TMP_DIR=$(mktemp -d)
BODY_FILE="$TMP_DIR/body.md"
INDEX_FILE="$TMP_DIR/index.md"
ERROR_FILE="$TMP_DIR/errors.log"
trap 'rm -rf -- "$TMP_DIR"' EXIT

: > "$BODY_FILE"
: > "$INDEX_FILE"
: > "$ERROR_FILE"

declare -A SEEN=()
TOTAL=0
FAILED=0

# Extract subcommand names from the commands list in Cobra-style help text.
extract_subcommands() {
  awk '
    /^(Available Commands|Additional help topics):[[:space:]]*$/ {
      in_commands = 1
      next
    }
    in_commands && /^[[:space:]]*$/ {
      in_commands = 0
      next
    }
    in_commands {
      line = $0
      sub(/^[[:space:]]+/, "", line)
      if (line ~ /^[[:alnum:]_-]+[[:space:]]+/) {
        split(line, fields, /[[:space:]]+/)
        print fields[1]
      }
    }
  ' | awk '!seen[$0]++'
}

make_github_anchor() {
  local value="$1"
  value=${value,,}
  value=${value// /-}
  value=${value//\//-}
  value=${value//_/}
  value=${value//\`/}
  printf '%s' "$value"
}

collect_help() {
  local -a command_path=("$@")
  local depth=${#command_path[@]}

  if ((depth > MAX_DEPTH)); then
    printf 'Max recursion depth exceeded, skipping: %s %s\n' \
      "$ROOT_NAME" "${command_path[*]}" >> "$ERROR_FILE"
    return
  fi

  local key="__root__"
  local display="$ROOT_NAME"
  if ((depth > 0)); then
    key="${command_path[*]}"
    display+=" ${command_path[*]}"
  fi

  [[ ${SEEN[$key]+exists} ]] && return
  SEEN[$key]=1
  ((TOTAL += 1))

  echo "🔎 $display --help"

  local -a invocation=("$SIYUAN_PATH")
  invocation+=("${command_path[@]}")
  invocation+=(--help)

  local help_text status=0
  help_text=$(LC_ALL=C "${invocation[@]}" 2>&1) || status=$?

  local anchor
  anchor=$(make_github_anchor "$display")
  printf -- '- [`%s`](#%s)\n' "$display" "$anchor" >> "$INDEX_FILE"

  {
    printf '## `%s`\n\n' "$display"
    printf 'Command: `%s --help`\n\n' "$display"
    printf '````text\n%s\n````\n\n' "$help_text"
  } >> "$BODY_FILE"

  if ((status != 0)); then
    ((FAILED += 1))
    printf '%s --help returned status %d\n' "$display" "$status" >> "$ERROR_FILE"
    return
  fi

  local -a children=()
  mapfile -t children < <(printf '%s\n' "$help_text" | extract_subcommands)

  local child
  for child in "${children[@]}"; do
    [[ -n "$child" ]] || continue
    collect_help "${command_path[@]}" "$child"
  done
}

VERSION=$(LC_ALL=C "$SIYUAN_PATH" --version 2>&1 || true)
GENERATED_AT=$(date '+%Y-%m-%d %H:%M:%S %z')

collect_help

FINAL_TMP="$TMP_DIR/final.md"
{
  printf '# SiYuan CLI Complete Help\n\n'
  printf '> This document was auto-generated by `%s` by recursively running `--help` on every subcommand.\n\n' "$ROOT_NAME"
  printf -- '- Generated at: `%s`\n' "$GENERATED_AT"
  printf -- '- CLI version: `%s`\n' "${VERSION//$'\n'/ }"
  printf -- '- Executable: `%s`\n' "$ROOT_NAME"
  printf -- '- Commands collected: `%d`\n' "$TOTAL"
  printf -- '- Help-read failures: `%d`\n\n' "$FAILED"
  printf 'The script only calls `--help` on each subcommand; it performs no document modifications, sync, imports, or deletions.\n\n'
  printf '## Command Index\n\n'
  cat "$INDEX_FILE"
  printf '\n'
  cat "$BODY_FILE"

  if [[ -s "$ERROR_FILE" ]]; then
    printf '## Warnings\n\n'
    printf '````text\n'
    cat "$ERROR_FILE"
    printf '````\n'
  fi
} > "$FINAL_TMP"

mv -- "$FINAL_TMP" "$OUTPUT_FILE"

printf '\n✅ SiYuan CLI help collection written to: %s\n' "$OUTPUT_FILE"
printf '   %d commands collected, %d failed.\n' "$TOTAL" "$FAILED"
